package generate

import (
	"encoding/json"
	"fmt"
	"path/filepath"
)

// GenerateProject generates a full project scaffold.
func GenerateProject(name string, withAuth bool) map[string]string {
	files := make(map[string]string)

	program := map[string]any{
		"name":    name,
		"go_json": "1",
		"server": map[string]any{
			"port":      3000,
			"static":    "public",
			"templates": "templates",
		},
		"import": map[string]any{
			"db": "io:sql",
		},
		"middleware": []string{"logger", "recover", "cors"},
		"routes": []map[string]any{
			{"method": "GET", "path": "/", "handler": "index"},
		},
		"functions": map[string]any{
			"index": map[string]any{
				"steps": []map[string]any{
					{"return": map[string]any{"status": 200, "body": map[string]string{"message": fmt.Sprintf("'Welcome to %s'", name)}}},
				},
			},
		},
	}

	if withAuth {
		program["server"].(map[string]any)["jwt"] = map[string]any{
			"secret_env": "JWT_SECRET",
			"algorithm":  "HS256",
			"expiry":     "24h",
		}
	}

	data, _ := json.MarshalIndent(program, "", "  ")
	files["api.json"] = string(data)

	files[filepath.Join("public", "index.html")] = fmt.Sprintf(`<!DOCTYPE html>
<html>
<head><title>%s</title></head>
<body><h1>%s</h1><p>Edit api.json to get started.</p></body>
</html>`, name, name)

	files[filepath.Join("templates", "index.html")] = `<!DOCTYPE html>
<html>
<head><title>{{.title}}</title></head>
<body>
<h1>{{.title}}</h1>
{{template "content" .}}
</body>
</html>`

	files[filepath.Join("templates", "content.html")] = `{{define "content"}}
<p>Welcome!</p>
{{end}}`

	files[".env.example"] = "PORT=3000\nDATABASE_URL=sqlite:./app.db\n"
	if withAuth {
		files[".env.example"] += "JWT_SECRET=your-secret-key-here\n"
		files[filepath.Join("migrations", "001_users.sql")] = GenerateAuthSQL()
	}

	files["README.md"] = fmt.Sprintf("# %s\n\nGenerated by go-json.\n\n```bash\ngo-json serve api.json\n```\n", name)

	return files
}
